# -*- coding: utf-8 -*-
"""Escreva um programa que ordene uma lista numérica com três elementos.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxSKPBjs7P80chhqprybWYo_VXnVjozB
"""

lista = [900,8,-583]

lista.sort()

print("Lista em ordem numérica:", lista)

