# -*- coding: utf-8 -*-
"""Escreva um programa que receba dois números e um sinal, e faça a operação matemática definida pelo sinal.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxSKPBjs7P80chhqprybWYo_VXnVjozB
"""

def calcular(numero1, numero2, sinal):
	if sinal == '+':
		resultado = numero1 + numero2
	elif sinal == '-':
		resultado = numero1 - numero2
	elif sinal == '*':
		resultado = numero1 * numero2
	elif sinal == '/':
		resultado = numero1 / numero2
	elif sinal == '**':
		resultado = numero1 ** numero2
	else:
		print("Sinal inválido")
		return None

	print("O resultado da operação é:", resultado)


numero1= float(input("Digite o primeiro número: "))
numero2= float(input("Digite o segundo número: "))
sinal= input("Digite o sinal da operação a ser feita (+,-./ ou *) ")

calcular(numero1, numero2, sinal)



