# -*- coding: utf-8 -*-
"""Escreva um programa que resolva uma equação de segundo grau.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxSKPBjs7P80chhqprybWYo_VXnVjozB
"""

import math

a = float(input("Digite o valor de a: "))
b = float(input("Digite o valor de b: "))
c = float(input("Digite o valor de c: "))

delta = b ** 2 - 4 * a * c

if a == 0:
    print("Para uma equação quadrática, 'a' deve ser diferente de 0")
elif delta > 0:
    raiz_de_delta = math.sqrt(delta)
    raiz_1 = (-b + raiz_de_delta) / (2 * a)
    raiz_2 = (-b - raiz_de_delta) / (2 * a)
    print("Resultado: raiz 1 =", raiz_1, "raiz 2 =", raiz_2)
elif delta == 0:
    raiz_1 = -b / (2 * a)
    print("Resultado: raiz única =", raiz_1)
else:
    print("A equação não possui raízes reais")

