# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxSKPBjs7P80chhqprybWYo_VXnVjozB
"""

nota_A1 = int(input("Digite sua nota A1 "))
nota_A2 = int(input("Digite sua nota A2 "))
nota_media = (nota_A1 + nota_A2) / 2

if nota_media >= 6:
	print("Você foi aprovado!")

else:
	print("Você foi reprovado!")

